#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys, argparse, subprocess, autoerp_lib

# Syntax: ./AutoERP-create <instance name> <suite name> <odoo version> <http port>

def Main():
    # See: https://docs.python.org/3/library/argparse.html
    parser = argparse.ArgumentParser(description='Creates AutoERP instances and installs suites on them.')
    
    parser.add_argument('instance_name',    type=str,   help='The instance name to create')
    parser.add_argument('suite_name',       type=str,   help='The suite name to install in the instance')
    parser.add_argument('odoo_version',     type=str,   help='The Odoo version to use')
    parser.add_argument('http_port',        type=int,   help='The HTTP port that the new instance opens')
    args = parser.parse_args()
    
    #######################################################
    ##### Do the install itself:        ###################
    #######################################################
    # Create ths installer:
    installer = autoerp_lib.InstanceInstaller(
        instancename    = args.instance_name,
        suitename       = args.suite_name,
        release_num     = args.odoo_version,
        httpport        = str(args.http_port),
        private         = False,
        )
    # Get an installed instance, which also make the material install itself:
    inst = installer.get_installed_instance()
    # Restart the instance via Systemctl:
    inst.restart_instance()
    # Install instance apps:
    inst.install_all_apps()
    
Main()
